/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juanmolina_lab.pkg7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class mainPanel extends javax.swing.JFrame {

    /**
     * Creates new form mainPanel
     */
    public mainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        EquiposMenu = new javax.swing.JMenu();
        ItemCrear = new javax.swing.JMenuItem();
        ItemModificar = new javax.swing.JMenuItem();
        ItemEliminar = new javax.swing.JMenuItem();
        ItemCargar = new javax.swing.JMenuItem();
        PartidosMenu = new javax.swing.JMenu();
        ItemSimulacion = new javax.swing.JMenuItem();
        ItemTabla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EquiposMenu.setText("Equipos");

        ItemCrear.setText("Crear");
        ItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCrearActionPerformed(evt);
            }
        });
        EquiposMenu.add(ItemCrear);

        ItemModificar.setText("Modificar");
        EquiposMenu.add(ItemModificar);

        ItemEliminar.setText("Eliminar");
        EquiposMenu.add(ItemEliminar);

        ItemCargar.setText("Cargar");
        EquiposMenu.add(ItemCargar);

        jMenuBar1.add(EquiposMenu);

        PartidosMenu.setText("Partidos");

        ItemSimulacion.setText("Simulacion");
        PartidosMenu.add(ItemSimulacion);

        ItemTabla.setText("Tabla");
        PartidosMenu.add(ItemTabla);

        jMenuBar1.add(PartidosMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPanel().setVisible(true);
            }
        });
    }
    
    ArrayList<equipo> equipos = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EquiposMenu;
    private javax.swing.JMenuItem ItemCargar;
    private javax.swing.JMenuItem ItemCrear;
    private javax.swing.JMenuItem ItemEliminar;
    private javax.swing.JMenuItem ItemModificar;
    private javax.swing.JMenuItem ItemSimulacion;
    private javax.swing.JMenuItem ItemTabla;
    private javax.swing.JMenu PartidosMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
